apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 825765405225.dkr.ecr.us-east-2.amazonaws.com/rakeshecr:latest
        ports:
        - containerPort: 80
